apiVersion: v2
name: github-sts-chart
description: GitHub Security Token Service (STS) - OIDC to GitHub token exchange
type: application
version: 0.1.2
appVersion: "0.1.1"
keywords:
  - github
  - oidc
  - authentication
  - security
  - sts
  - token-exchange
home: https://github.com/AlexandreODelisle/py-github-sts
sources:
  - https://github.com/AlexandreODelisle/py-github-sts
