blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/AlexandreODelisle/py-github-sts#readme
    about: Read the project documentation before opening an issue.
