{{- if and .Values.github.appId .Values.github.appPrivateKey (not .Values.github.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-sts.fullname" . }}-credentials
  labels:
    {{- include "github-sts.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-app-id: {{ .Values.github.appId | quote }}
  github-app-private-key: {{ .Values.github.appPrivateKey | quote }}
{{- end }}
