{{- if not .Values.github.existingSecret }}
{{- if or (not .Values.github.appId) (not .Values.github.appPrivateKey) }}
{{- fail "Either github.existingSecret must be set, or both github.appId and github.appPrivateKey must be provided." }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-sts.fullname" . }}-credentials
  labels:
    {{- include "github-sts.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-app-id: {{ .Values.github.appId | quote }}
  github-app-private-key: |
    {{- .Values.github.appPrivateKey | nindent 4 }}
{{- end }}
