{{- if and (not .Values.github.existingSecret) .Values.github.appId .Values.github.appPrivateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-sts.credentialsSecretName" . }}
  labels:
    {{- include "github-sts.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-app-id: {{ .Values.github.appId | quote }}
  github-app-private-key: |
    {{- .Values.github.appPrivateKey | nindent 4 }}
{{- end }}
